### ISSUE TITLE
OpenCV version

### ISSUE THREAD

**Issue by shubhamagarwal92** [Maluuba/GeNeVA_datasets#2]
Is the version of OpenCV 3.4.2 as mentioned in `environment.yml`? 

I tried to run `scripts/codraw_dataset_generation/codraw_raw_to_hdf5.py`, however I am getting this assertion error.  

```
Traceback (most recent call last):
  File "scripts/codraw_dataset_generation/codraw_raw_to_hdf5.py", line 187, in <module>
    create_h5()
  File "scripts/codraw_dataset_generation/codraw_raw_to_hdf5.py", line 153, in create_h5
    image = cv2.resize(image, (128, 128))
cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

I installed opencv using `pip install opencv-python==3.4.2.17`

**Comment by shubhamagarwal92** [comment]
Never mind, I had some directory issues!
